name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 작동

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 파일 압축
      - name: Zip handler.py
        run: zip -r handler.py.zip handler.py

      # 3. AWS CLI 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 지역에 맞게 변경

      # 4. 환경 변수에서 S3 버킷 이름 가져오기
      - name: Export S3 Bucket Name from Variables
        run: echo "BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> $GITHUB_ENV

      # 5. index.html 업로드
      - name: Upload page files and handler.py to S3
        run: |
          aws s3 cp index.html s3://$BUCKET_NAME/
          aws s3 cp index.css s3://$BUCKET_NAME/
          aws s3 cp handler.py.zip s3://$BUCKET_NAME/
